// Single source of truth for Rita Chen's Q1 selling quarter.
// All views (Today, Sales, Salesforce Channel tabs) read from here.
// READ-ONLY — views render from this, never mutate it.

export const RITA_DATA = {
  seller: {
    name: "Rita Chen",
    role: "Account Executive, Mid-Market",
    avatar: null,
    quota: 500000,
    ote: 140000,
    commissionAtQuota: 70000,
  },

  q4: {
    attainment: 471000,
    quotaPct: 94,
    quota: 500000,
    winRate: 52,
    avgDealSize: 38000,
    avgSalesCycle: 47,
    dealsClosed: 12,
    personalCloseRate: 68,
    delegatedCloseRate: 41,
    missedAccelerator: 29000,
    lostCommission: 4200,
    slippedDeals: 3,
    pricingError: 1,
    missedSignal: 1,
  },

  q1Pipeline: {
    total: 1200000,
    activeDeals: 14,
    weighted: 624000,
    onTrack:      { count: 4, value: 410000 },
    needsNurture: { count: 6, value: 480000 },
    cooling:      { count: 3, value: 220000 },
    atRisk:       { count: 1, value: 90000 },
  },

  deals: [
    {
      id: "deal-acme",
      name: "Acme Corp",
      channel: "deal-acme",
      amount: 89000,
      stage: "Negotiation",
      stageNumber: 4,
      closeDate: "Feb 28, 2025",
      champion: "Priya Shah",
      championTitle: "VP Engineering",
      decisionMaker: "Daniel Kim",
      decisionMakerTitle: "CTO",
      health: "cooling" as const,
      lastTouch: "Dec 28",
      lastTouchType: "Email — proposal follow-up",
      nextStep: "Exec intro via Sarah → Daniel Kim",
      sentiment: 78,
      competitors: ["ServiceNow", "Freshworks"],
      teamMembers: ["Mike Torres (SE)", "Sarah Chen (Manager)", "Legal"],
      recentActivity: [
        { who: "Rita Chen",  when: "Today",      what: "Sent intro to Priya via Sarah. Daniel Kim — can we pull the exec intro forward?" },
        { who: "Priya Shah", when: "2 days ago", what: "Responded to pricing proposal. Asked about volume discounts for 3-yr term." },
        { who: "Mike Torres",when: "3 days ago", what: "Technical appendix v3 shared. HIPAA section updated with new compliance notes." },
      ],
      record: {
        opportunityId: "006Dn000003xKPQ",
        accountId: "001Dn000004ABCD",
        type: "New Business",
        forecastCategory: "Commit",
        probability: 75,
        created: "Oct 15, 2024",
        owner: "Rita Chen",
        contacts: [
          { name: "Priya Shah",  title: "VP Engineering",    role: "Champion",        lastContact: "Dec 28" },
          { name: "Daniel Kim",  title: "CTO",               role: "Decision Maker",  lastContact: "Dec 12" },
          { name: "Anil Gupta",  title: "IT Director",       role: "Evaluator",       lastContact: "Dec 18" },
        ],
        activityTimeline: [
          { date: "Dec 28", type: "email",    label: "Email to Priya — proposal follow-up" },
          { date: "Dec 22", type: "call",     label: "Call with Daniel — exec alignment" },
          { date: "Dec 18", type: "call",     label: "Call with Anil — technical review" },
          { date: "Dec 15", type: "doc",      label: "Proposal v2 sent" },
          { date: "Dec 12", type: "meeting",  label: "Meeting — Daniel + Priya + Rita" },
        ],
        activities: 47,
        openTasks: 2,
      },
      relatedOpportunities: [
        { name: "Acme Corp — Support Renewal",  amount: 24000, stage: "Closed Won", date: "Q4" },
        { name: "Acme Corp — Training Package", amount: 12000, stage: "Proposal",   date: "Mar 30" },
      ],
      cases: [
        { id: "#00045821", title: "Integration timeout issue", priority: "Medium", opened: "Dec 20", assignedTo: "Support Team" },
      ],
      quotes: [
        { id: "Q-00123", amount: 89000, status: "Presented", date: "Dec 15", products: "Platform License (3yr), Premium Support" },
      ],
      files: [
        { name: "Acme_Proposal_v3.pdf",          date: "Dec 15", author: "Rita Chen",   type: "pdf" },
        { name: "Technical_Appendix_HIPAA.docx", date: "Dec 18", author: "Mike Torres", type: "doc" },
        { name: "Acme_MSA_Draft.pdf",            date: "Dec 22", author: "Legal",       type: "pdf" },
        { name: "ROI_Calculator_Acme.xlsx",      date: "Dec 10", author: "Rita Chen",   type: "sheet" },
      ],
    },
    {
      id: "deal-greentech",
      name: "Greentech Solutions",
      channel: "deal-greentech",
      amount: 60000,
      stage: "Proposal",
      stageNumber: 3,
      closeDate: "Mar 15, 2025",
      champion: "Diane Park",
      championTitle: "CIO",
      decisionMaker: "Diane Park",
      decisionMakerTitle: "CIO",
      health: "on-track" as const,
      lastTouch: "Dec 30",
      lastTouchType: "Lunch meeting — relationship building",
      nextStep: "SOW review scheduled Jan 8",
      sentiment: 82,
      competitors: ["None identified"],
      teamMembers: ["Priya Shah (SE)", "Sarah Chen (Manager)"],
      recentActivity: [
        { who: "Rita Chen",  when: "Today",      what: "Following up with Priya on SOW. She's been very responsive." },
        { who: "Diane Park", when: "3 days ago", what: "Confirmed budget allocation for Q1. Moving forward with review." },
      ],
      record: {
        opportunityId: "006Dn000003xKPR",
        accountId: "001Dn000004EFGH",
        type: "New Business",
        forecastCategory: "Best Case",
        probability: 60,
        created: "Nov 2, 2024",
        owner: "Rita Chen",
        contacts: [
          { name: "Diane Park",  title: "CIO",           role: "Champion / Decision Maker", lastContact: "Dec 30" },
          { name: "Tom Reeves",  title: "VP Operations", role: "Influencer",                lastContact: "Dec 15" },
        ],
        activityTimeline: [
          { date: "Dec 30", type: "meeting", label: "Lunch meeting — relationship building with Diane" },
          { date: "Dec 20", type: "doc",     label: "Proposal v1 sent" },
          { date: "Dec 15", type: "call",    label: "Discovery call with Tom Reeves — ops use cases" },
          { date: "Dec 10", type: "email",   label: "Intro email from Sarah's referral" },
        ],
        activities: 28,
        openTasks: 1,
      },
      relatedOpportunities: [],
      cases: [],
      quotes: [
        { id: "Q-00118", amount: 60000, status: "Draft", date: "Dec 20", products: "Platform License (2yr), Standard Support" },
      ],
      files: [
        { name: "Greentech_Proposal_v1.pdf",  date: "Dec 20", author: "Rita Chen",  type: "pdf" },
        { name: "Greentech_SOW_Draft.docx",   date: "Dec 28", author: "Priya Shah", type: "doc" },
      ],
    },
    {
      id: "deal-novacorp",
      name: "NovaCorp",
      channel: "deal-novacorp",
      amount: 45000,
      stage: "Legal Review",
      stageNumber: 5,
      closeDate: "Jan 31, 2025",
      champion: "Marcus Lee",
      championTitle: "Head of Procurement",
      decisionMaker: "Marcus Lee",
      decisionMakerTitle: "Head of Procurement",
      health: "needs-nurture" as const,
      lastTouch: "Dec 22",
      lastTouchType: "Contract sent — standard MSA terms",
      nextStep: "Waiting on legal redlines (overdue 3 days)",
      sentiment: 65,
      competitors: ["Competitor X — legacy incumbent"],
      teamMembers: ["Legal Team", "Sarah Chen (Manager)"],
      recentActivity: [
        { who: "Priya Shah",  when: "10:20 AM",    what: "MSA is ready. Just need their legal to review clause 7.2. Can you confirm the non-standard terms?" },
        { who: "Marcus Lee",  when: "1 week ago",  what: "Confirmed budget allocation. Standard redlines expected." },
      ],
      record: {
        opportunityId: "006Dn000003xKPS",
        accountId: "001Dn000004IJKL",
        type: "New Business",
        forecastCategory: "Commit",
        probability: 85,
        created: "Sep 20, 2024",
        owner: "Rita Chen",
        contacts: [
          { name: "Marcus Lee",    title: "Head of Procurement", role: "Champion",  lastContact: "Dec 22" },
          { name: "Sandra Nguyen", title: "General Counsel",     role: "Legal",     lastContact: "Dec 22" },
        ],
        activityTimeline: [
          { date: "Dec 22", type: "doc",   label: "Contract sent — standard MSA terms" },
          { date: "Dec 18", type: "call",  label: "Legal review kickoff call with Sandra" },
          { date: "Dec 15", type: "email", label: "Final pricing confirmation to Marcus" },
          { date: "Dec 10", type: "doc",   label: "Security questionnaire completed" },
        ],
        activities: 52,
        openTasks: 3,
      },
      relatedOpportunities: [],
      cases: [],
      quotes: [
        { id: "Q-00115", amount: 45000, status: "Accepted", date: "Dec 15", products: "Platform License (1yr), Standard Support" },
      ],
      files: [
        { name: "NovaCorp_MSA_v1.pdf",       date: "Dec 22", author: "Legal",      type: "pdf" },
        { name: "Security_Questionnaire.pdf", date: "Dec 10", author: "Mike Torres",type: "pdf" },
      ],
    },
    {
      id: "deal-runners",
      name: "Runners Inc",
      channel: "deal-runners",
      amount: 72000,
      stage: "Closed Won",
      stageNumber: 6,
      closeDate: "Jan 2, 2025",
      champion: "Mike Torres",
      championTitle: "VP Ops",
      decisionMaker: "Mike Torres",
      decisionMakerTitle: "VP Ops",
      health: "on-track" as const,
      lastTouch: "Today",
      lastTouchType: "Contract signed — Q1 commit locked",
      nextStep: "Handoff to CSM (Lisa Park)",
      sentiment: 95,
      competitors: [],
      teamMembers: ["Jordan Hayes (SE)", "Sarah Chen (Manager)"],
      recentActivity: [
        { who: "Mike Torres", when: "Today",       what: "Confirmed they'll sign by EOD Friday. Q1 commit locked in. 🎉" },
        { who: "Priya Shah",  when: "1 week ago",  what: "Contract draft sent. Standard MSA terms, no redlines expected." },
        { who: "Rita Chen",   when: "2 weeks ago", what: "POC completed successfully. Moving to contract discussions." },
      ],
      record: {
        opportunityId: "006Dn000003xKPT",
        accountId: "001Dn000004MNOP",
        type: "New Business",
        forecastCategory: "Closed",
        probability: 100,
        created: "Oct 1, 2024",
        owner: "Rita Chen",
        contacts: [
          { name: "Mike Torres",  title: "VP Ops",         role: "Champion",   lastContact: "Today" },
          { name: "Jordan Hayes", title: "Dir Engineering", role: "Evaluator",  lastContact: "3 weeks ago" },
        ],
        activityTimeline: [
          { date: "Jan 2",  type: "doc",     label: "Contract signed — closed won" },
          { date: "Dec 26", type: "doc",     label: "Contract sent — MSA v2 final" },
          { date: "Dec 20", type: "meeting", label: "Final commercial review — Mike + Rita" },
          { date: "Dec 15", type: "call",    label: "POC sign-off call with Jordan Hayes" },
          { date: "Dec 10", type: "doc",     label: "Proposal v2 accepted" },
        ],
        activities: 61,
        openTasks: 0,
      },
      relatedOpportunities: [],
      cases: [],
      quotes: [
        { id: "Q-00121", amount: 72000, status: "Accepted", date: "Dec 26", products: "Platform License (2yr), Premium Support" },
      ],
      files: [
        { name: "Runners_Inc_Contract_Final.pdf", date: "Jan 2",  author: "Legal",      type: "pdf" },
        { name: "Runners_Inc_Proposal_v2.pdf",    date: "Dec 10", author: "Rita Chen",  type: "pdf" },
      ],
    },
    {
      id: "deal-sporty",
      name: "Sporty Nation",
      channel: "deal-sporty",
      amount: 270000,
      stage: "Discovery",
      stageNumber: 1,
      closeDate: "Mar 31, 2025",
      champion: "Unknown",
      championTitle: "",
      decisionMaker: "Chris Park",
      decisionMakerTitle: "VP Digital",
      health: "at-risk" as const,
      lastTouch: "Dec 18",
      lastTouchType: "Discovery call — champion silent since",
      nextStep: "Re-engage champion. 14 days silent.",
      sentiment: 32,
      competitors: ["SAP", "Oracle"],
      teamMembers: ["Dana Torres (SE)"],
      recentActivity: [
        { who: "Dana Torres", when: "Today", what: "14 days silent. Champion gone dark. Should we escalate to their VP Digital?" },
      ],
      record: {
        opportunityId: "006Dn000003xKPU",
        accountId: "001Dn000004QRST",
        type: "New Business",
        forecastCategory: "Pipeline",
        probability: 20,
        created: "Nov 15, 2024",
        owner: "Rita Chen",
        contacts: [
          { name: "Chris Park", title: "VP Digital", role: "Initial Contact", lastContact: "Dec 18" },
        ],
        activityTimeline: [
          { date: "Dec 18", type: "call",  label: "Discovery call with Chris Park — initial requirements" },
          { date: "Dec 10", type: "email", label: "Intro email + discovery agenda sent" },
          { date: "Nov 28", type: "call",  label: "Cold outreach — qualified interest" },
        ],
        activities: 8,
        openTasks: 1,
      },
      relatedOpportunities: [],
      cases: [],
      quotes: [],
      files: [
        { name: "Sporty_Nation_Discovery_Notes.docx", date: "Dec 18", author: "Rita Chen", type: "doc" },
      ],
    },
  ],

  team: [
    { name: "Sarah Chen",  role: "Sales Manager",       initials: "SC" },
    { name: "Mike Torres", role: "Solutions Engineer",  initials: "MT" },
    { name: "Priya Shah",  role: "Solutions Engineer",  initials: "PS" },
    { name: "Jordan Hayes",role: "Solutions Engineer",  initials: "JH" },
    { name: "Dana Torres", role: "Solutions Engineer",  initials: "DT" },
    { name: "Marcus Lee",  role: "Legal Liaison",       initials: "ML" },
    { name: "Lisa Park",   role: "CSM",                 initials: "LP" },
  ],

  today: {
    date: "January 2",
    dayOfWeek: "Thursday",
    meetings: [
      { time: "10:00 AM", title: "Weekly Team Sync",          type: "zoom",        deal: null,           context: "Q1 kickoff — your plan auto-shared with Sarah" },
      { time: "11:30 AM", title: "Discovery Call — Acme Corp",type: "phone",       deal: "deal-acme",    context: "Champion: Priya Shah · Last touch: Dec 28 · Sentiment: Strong · Prep brief ready" },
      { time: "1:00 PM",  title: "Lunch — Diane Park (CIO, Greentech)", type: "in-person", deal: "deal-greentech", context: "Relationship meeting · $60K · Stage 3 · No formal agenda" },
      { time: "2:30 PM",  title: "NovaCorp Legal Sync",       type: "internal",    deal: "deal-novacorp", context: "Clause 7.2 review · Standard redlines · 15 min" },
      { time: "4:00 PM",  title: "1:1 with Sarah Chen",       type: "zoom",        deal: null,           context: "Agenda auto-generated: Q1 plan, Acme risk, Greentech strategy, Sporty reactivation" },
      { time: "5:00 PM",  title: "Sporty Nation Internal Review", type: "huddle",  deal: "deal-sporty",  context: "14 days silent · Need reactivation strategy · Dana joining" },
    ],
    actionItems: [
      { title: "Review Priya's Dec 28 email re: volume discount request", source: "Priya Shah", sourceType: "email",   age: "5 days ago", deal: "deal-acme" },
      { title: "Respond to Mike's technical question on Acme appendix",   source: "Mike Torres", sourceType: "slack",  age: "3 days ago", deal: "deal-acme" },
      { title: "Sign off on Greentech proposal v3",                       source: "Legal",       sourceType: "slack",  age: "1 day ago",  deal: "deal-greentech" },
      { title: "Update PRD with latest user research findings",           source: "Elliott",     sourceType: "mention", age: "5 days ago", deal: null },
    ],
    repliesNeeded: [
      { from: "Priya Shah",  channel: "#deal-novacorp", preview: "MSA is ready. Just need their legal to review clause 7.2. Can you confirm the non-standard terms?", time: "10:20 AM", initials: "PS" },
      { from: "Sarah Chen",  channel: "DM",             preview: "Keep me posted. Pipeline hygiene is looking good but I want to discuss Sporty Nation reactivation in our 1:1.", time: "Today", initials: "SC" },
      { from: "Dana Torres", channel: "#deal-sporty",   preview: "14 days silent. Champion gone dark. Should we escalate to their VP Digital?", time: "Today", initials: "DT" },
    ],
    highlights: [
      {
        channel: "#deal-runners",
        summary: "Mike confirmed they'll sign by EOD Friday. Q1 commit locked in. $72K closed.",
        mentions: ["Mike Torres", "Priya Shah", "Jordan Hayes"],
        time: "Today",
        sentiment: "positive" as const,
        reactions: [{ emoji: "🎉", count: 3 }, { emoji: "🚀", count: 2 }],
        replies: 4,
      },
      {
        channel: "#deal-acme",
        summary: "Sent intro to Priya via Sarah. Daniel Kim exec-to-exec intro being set up for Jan 8.",
        mentions: ["Rita Chen", "Sarah Chen"],
        time: "Today",
        sentiment: "positive" as const,
        reactions: [{ emoji: "👍", count: 2 }],
        replies: 1,
      },
      {
        channel: "#q3-pipeline",
        summary: "Sporty Nation ($270K) flagged as high risk. Champion silent for 14 days. No response to last 3 outreach attempts.",
        mentions: ["Dana Torres"],
        time: "Today",
        sentiment: "warning" as const,
        reactions: [{ emoji: "⚠️", count: 1 }],
        replies: 2,
      },
      {
        channel: "#general",
        summary: "Champion departed: Acme Corp. Daniel Kim's EA confirmed his calendar is being cleared through January.",
        mentions: [],
        time: "10:36 AM",
        sentiment: "critical" as const,
        reactions: [],
        replies: 0,
      },
    ],
  },
} as const;

// Health dot colors — consistent across all views
export const HEALTH_COLORS = {
  "on-track":     { dot: "#22C55E", bg: "#F0FDF4", text: "#16A34A", label: "On Track" },
  "needs-nurture":{ dot: "#EAB308", bg: "#FEFCE8", text: "#CA8A04", label: "Needs Nurture" },
  "cooling":      { dot: "#F97316", bg: "#FFF7ED", text: "#EA580C", label: "Cooling" },
  "at-risk":      { dot: "#EF4444", bg: "#FEF2F2", text: "#DC2626", label: "At Risk" },
} as const;

export type Deal = typeof RITA_DATA.deals[number];
export type DealHealth = keyof typeof HEALTH_COLORS;
